# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # Ubuntu 14.04 LTS VM image
  config.vm.box = "ubuntu/trusty64"

  # Set VM name
  config.vm.provider :virtualbox do |vb|
    vb.name = "ubuntu-trusty64"
    vb.memory = 2048
    vb.cpus = 1
    config.vm.network "public_network", type: "dhcp", bridge: "eth1"
    config.vm.provision :shell, path: "bootstrap.sh"
  end

end
